GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjMDFhYjYyMzk1NTYzYTNkMmMyZGYiLCJpYXQiOjE2NzQzMTQ4ODEsImV4cCI6MTY3NDkxOTY4MX0.AUk4G6Q-rZECLfr5r3RAf8SxgXxZq8CUtx49i7uZysM
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlkZDQ5NzhlYzA3MTNjNDQ4NWY0MzAiLCJpYXQiOjE2NzEyODc5OTQsImV4cCI6MTY3MTg5Mjc5NH0.B93VNkxWJuthkOrX16PuWDVkw6Nwfy9KzcMXwcgAvIk
Accept: application/json

###
PATCH http://localhost:3000/users/me
Accept: application/json

###
GET http://localhost:3000/movies/
Accept: application/json

###

POST http://localhost:3000/movies/
Accept: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlkZDQ5NzhlYzA3MTNjNDQ4NWY0MzAiLCJpYXQiOjE2NzEyODc5OTQsImV4cCI6MTY3MTg5Mjc5NH0.B93VNkxWJuthkOrX16PuWDVkw6Nwfy9KzcMXwcgAvIk
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjMDFhYjYyMzk1NTYzYTNkMmMyZGYiLCJpYXQiOjE2NzQzMTQ4ODEsImV4cCI6MTY3NDkxOTY4MX0.AUk4G6Q-rZECLfr5r3RAf8SxgXxZq8CUtx49i7uZysM
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjZjNhNjcyMTA2ZjE2ZDAwMGZjZDMiLCJpYXQiOjE2NzQzNzYyMDEsImV4cCI6MTY3NDk4MTAwMX0.Hfu0UNfFlMsGU2qNcDhxCSlX69Arhpg91L7bqVmhehc
Content-Type: application/json

{
  "country": "22222Россияжжж,,,GER GER11",
  "director": "Виталя",
  "duration": "26",
  "year": "1990 год",
  "description": "Тупой фильм",
  "image": "https://ic.pics.livejournal.com/bav_eot/44066703/942996/942996_original.jpg",
  "trailerLink": "https://ic.pics.livejournal.com/bav_eot/44066703/942996/942996_original.jpg",
  "thumbnail": "https://ic.pics.livejournal.com/bav_eot/44066703/942996/942996_original.jpg",
  "id": "kdaskdmlkzxmlxk ksxzmnxm",
  "nameRU": "Ромка",
  "nameEN": "Romka"
}
###

DELETE http://localhost:3000/movies/63ccf4a772106f16d000fcde
//Accept: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk1ZmFlNDkwY2RiMGRlMWM4ODZjM2QiLCJpYXQiOjE2NzA4NjkyNTksImV4cCI6MTY3MTQ3NDA1OX0.nHcKs385f_KQKUDVv0fT5jffMQUVJSmbPXU_ABj9y6o
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjMDFhYjYyMzk1NTYzYTNkMmMyZGYiLCJpYXQiOjE2NzQzMTQ4ODEsImV4cCI6MTY3NDkxOTY4MX0.AUk4G6Q-rZECLfr5r3RAf8SxgXxZq8CUtx49i7uZysM
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjZjNhNjcyMTA2ZjE2ZDAwMGZjZDMiLCJpYXQiOjE2NzQzNzYyMDEsImV4cCI6MTY3NDk4MTAwMX0.Hfu0UNfFlMsGU2qNcDhxCSlX69Arhpg91L7bqVmhehc


###

POST http://localhost:3000/signup
Accept: application/json
Content-Type: application/json

{
  "email": "vitlas11ppas@ddwssssaasaslladdddllll.ru",
  "password": "mnlmkkdadjja",
  "name": "PPPPPPsP"
}
###

POST http://localhost:3000/signin
Accept: application/json
Content-Type: application/json

{
  "email": "vitla@ddwssssaasaslladdddllll.ru",
  "password": "mnlmkkdadjja"
}
###
GET http://localhost:3000/movies
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk1ZmFlNDkwY2RiMGRlMWM4ODZjM2QiLCJpYXQiOjE2NzA4NjkyNTksImV4cCI6MTY3MTQ3NDA1OX0.nHcKs385f_KQKUDVv0fT5jffMQUVJSmbPXU_ABj9y6o
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjMDFhYjYyMzk1NTYzYTNkMmMyZGYiLCJpYXQiOjE2NzQzMTQ4ODEsImV4cCI6MTY3NDkxOTY4MX0.AUk4G6Q-rZECLfr5r3RAf8SxgXxZq8CUtx49i7uZysM
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjZjNhNjcyMTA2ZjE2ZDAwMGZjZDMiLCJpYXQiOjE2NzQzNzYyMDEsImV4cCI6MTY3NDk4MTAwMX0.Hfu0UNfFlMsGU2qNcDhxCSlX69Arhpg91L7bqVmhehc
###
PATCH http://localhost:3000/users/me
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjMDFhYjYyMzk1NTYzYTNkMmMyZGYiLCJpYXQiOjE2NzQzMTQ4ODEsImV4cCI6MTY3NDkxOTY4MX0.AUk4G6Q-rZECLfr5r3RAf8SxgXxZq8CUtx49i7uZysM
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjZjNhNjcyMTA2ZjE2ZDAwMGZjZDMiLCJpYXQiOjE2NzQzNzYyMDEsImV4cCI6MTY3NDk4MTAwMX0.Hfu0UNfFlMsGU2qNcDhxCSlX69Arhpg91L7bqVmhehc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2NjZjNhNjcyMTA2ZjE2ZDAwMGZjZDMiLCJpYXQiOjE2NzQzNzYyMDEsImV4cCI6MTY3NDk4MTAwMX0.Hfu0UNfFlMsGU2qNcDhxCSlX69Arhpg91L7bqVmhehc
Accept: application/json
Content-Type: application/json

{
  "email": "vitla@aslladdddllll.ru",
  "name": "Vitaliy888"
}
###


//2-ой пользовьтель
###

POST http://localhost:3000/signup
Accept: application/json
Content-Type: application/json

{
  "email": "vitlas@ddd11ppasd.ru",
  "password": "mnlmkkdadjja",
  "name": "was"
}
###

POST http://localhost:3000/signin
Accept: application/json
Content-Type: application/json

{
  "email": "vitlas@11ppas-ddwlЮ.ru",
  "password": "mnlmkkdadjja"
}
###